import type { GameAction } from "../../types/game";

export const cityActions: GameAction[] = [
  {
    id: "activate-grid-sensors",
    label: "Aktywuj czujniki sieci",
    cyberneticPart: "receptor",
    description: "Miasto odbiera dane o stanie infrastruktury energetycznej.",
    effects: { informationQuality: 5 },
    goodForMissionIds: ["power-outage"],
    feedbackGood: "Receptor miejski odebrał sygnał z sieci. System ma dane wejściowe zamiast domysłów.",
  },
  {
    id: "activate-social-listening",
    label: "Zbierz sygnały społeczne",
    cyberneticPart: "receptor",
    description: "Receptory społeczne pokazują nastroje mieszkańców.",
    effects: { informationQuality: 8, trust: 2 },
    goodForMissionIds: ["disinformation", "trust-crisis"],
    feedbackGood: "Zgłoszenia mieszkańców i media są receptorami społecznymi. Bez nich miasto nie zna własnego stanu.",
  },
  {
    id: "activate-traffic-sensors",
    label: "Aktywuj czujniki ruchu",
    cyberneticPart: "receptor",
    description: "Pętle, kamery i dane transportowe mierzą przepływy w mieście.",
    effects: { informationQuality: 7, transport: 2 },
    goodForMissionIds: ["traffic-jam"],
  },
  {
    id: "activate-water-stations",
    label: "Sprawdź stacje pomiaru wody",
    cyberneticPart: "receptor",
    description: "Receptory infrastrukturalne pokazują realny poziom zasobów wody.",
    effects: { informationQuality: 7 },
    goodForMissionIds: ["water-shortage", "disinformation"],
  },
  {
    id: "analyze-in-city-hall",
    label: "Przeanalizuj w centrum miasta",
    cyberneticPart: "correlator",
    description: "Ratusz, centrum danych i sztab kryzysowy kojarzą sygnały z reakcjami.",
    effects: { informationQuality: 6, stress: -2 },
    goodForMissionIds: ["power-outage", "disinformation", "traffic-jam", "water-shortage", "trust-crisis"],
    feedbackGood: "Korelator połączył dane z możliwą reakcją. Decyzja nie jest jeszcze wykonaniem.",
  },
  {
    id: "check-city-homeostat",
    label: "Sprawdź homeostat miasta",
    cyberneticPart: "homeostat",
    description: "Panel równowagi pokazuje, które parametry wyszły poza normę.",
    effects: {},
    goodForMissionIds: ["power-outage", "disinformation", "traffic-jam", "water-shortage", "trust-crisis"],
    feedbackGood: "Homeostat miejski pokazuje odchylenia: stabilność zależy od wielu parametrów naraz.",
  },
  {
    id: "use-energy-reserves",
    label: "Uruchom rezerwy energii",
    cyberneticPart: "accumulator",
    description: "Akumulator miasta oddaje zapasy energii.",
    effects: { energy: 15, resourceReserve: -15 },
    goodForMissionIds: ["power-outage"],
    badForMissionIds: ["water-shortage"],
    feedbackGood: "Akumulator oddaje rezerwy. Pomaga teraz, ale zmniejsza odporność na kolejne zakłócenie.",
  },
  {
    id: "repair-power-grid",
    label: "Wyślij ekipy techniczne",
    cyberneticPart: "effector",
    description: "Efektory miasta wykonują naprawę infrastruktury.",
    effects: { energy: 12, publicOrder: 4, resourceReserve: -5, stress: -4 },
    goodForMissionIds: ["power-outage"],
  },
  {
    id: "reduce-grid-load",
    label: "Ogranicz zbędne zużycie",
    cyberneticPart: "homeostat",
    description: "Procedury stabilizują sieć przez czasowe ograniczenie obciążenia.",
    effects: { energy: 8, stress: 3, trust: -1 },
    goodForMissionIds: ["power-outage"],
  },
  {
    id: "publish-transparent-message",
    label: "Opublikuj jasny komunikat",
    cyberneticPart: "effector",
    description: "Kanały informacji zmniejszają niepewność, jeśli komunikat jest zgodny z faktami.",
    effects: { trust: 8, stress: -8, informationQuality: 5, publicOrder: 3 },
    goodForMissionIds: ["power-outage", "disinformation", "trust-crisis", "water-shortage", "traffic-jam"],
    feedbackGood: "Komunikat działa jako efektor społeczny, ale jego skuteczność zależy od faktów i zaufania.",
  },
  {
    id: "show-measurement-data",
    label: "Pokaż dane z pomiarów",
    cyberneticPart: "effector",
    description: "Miasto udostępnia dowody, aby domknąć pętlę informacji.",
    effects: { informationQuality: 10, trust: 7, stress: -5 },
    goodForMissionIds: ["disinformation", "water-shortage", "trust-crisis"],
  },
  {
    id: "publish-empty-propaganda",
    label: "Wyślij pusty komunikat propagandowy",
    cyberneticPart: "effector",
    description: "Komunikat bez realnych działań chwilowo obniża napięcie, ale szkodzi zaufaniu.",
    effects: { stress: -3, trust: -10, informationQuality: -5 },
    badForMissionIds: ["disinformation", "trust-crisis", "power-outage"],
    feedbackBad: "Sama propaganda bez realnej poprawy zmniejsza zaufanie. Informacja musi być wiarygodna.",
  },
  {
    id: "reroute-traffic",
    label: "Przekieruj ruch",
    cyberneticPart: "effector",
    description: "Zmiana przepływu transportu odciąża przeciążony węzeł.",
    effects: { transport: 12, stress: -4 },
    goodForMissionIds: ["traffic-jam"],
  },
  {
    id: "adjust-traffic-lights",
    label: "Zmień sygnalizację",
    cyberneticPart: "correlator",
    description: "Korelator steruje przepływem na podstawie danych z receptorów.",
    effects: { transport: 8, informationQuality: 2 },
    goodForMissionIds: ["traffic-jam"],
  },
  {
    id: "send-road-services",
    label: "Wyślij służby drogowe",
    cyberneticPart: "effector",
    description: "Służby miejskie wykonują decyzję systemu.",
    effects: { transport: 8, publicOrder: 4, resourceReserve: -4 },
    goodForMissionIds: ["traffic-jam"],
  },
  {
    id: "close-main-road",
    label: "Zamknij główną arterię bez objazdu",
    cyberneticPart: "effector",
    description: "Silna reakcja bez alternatywy przenosi problem na inne przepływy.",
    effects: { transport: -16, stress: 10, trust: -6 },
    badForMissionIds: ["traffic-jam"],
  },
  {
    id: "limit-nonessential-water-use",
    label: "Ogranicz niekrytyczne zużycie wody",
    cyberneticPart: "homeostat",
    description: "Homeostat stabilizuje system przez ograniczenie odchylenia.",
    effects: { water: 10, stress: 4, trust: -2 },
    goodForMissionIds: ["water-shortage"],
  },
  {
    id: "open-water-reserves",
    label: "Uruchom rezerwy wody",
    cyberneticPart: "accumulator",
    description: "Miasto korzysta z akumulatora zasobów.",
    effects: { water: 15, resourceReserve: -12 },
    goodForMissionIds: ["water-shortage"],
  },
  {
    id: "activate-alternative-supply",
    label: "Uruchom alternatywne dostawy",
    cyberneticPart: "alimentator",
    description: "Alimentator miasta zwiększa dopływ zasobów przez wodociągi, cysterny lub dostawy.",
    effects: { water: 12, resourceReserve: -5, publicOrder: 2 },
    goodForMissionIds: ["water-shortage"],
  },
  {
    id: "real-repair-actions",
    label: "Wykonaj realne działania naprawcze",
    cyberneticPart: "effector",
    description: "Instytucje wykonują widoczne działania, które mogą odbudować zaufanie.",
    effects: { trust: 12, publicOrder: 6, resourceReserve: -6, stress: -5 },
    goodForMissionIds: ["trust-crisis"],
  },
  {
    id: "reduce-message-overload",
    label: "Ogranicz przeciążenie komunikatami",
    cyberneticPart: "homeostat",
    description: "Homeostat społeczny zmniejsza szum informacyjny i ułatwia orientację.",
    effects: { informationQuality: 7, stress: -6, trust: 3 },
    goodForMissionIds: ["trust-crisis", "disinformation"],
  },
  {
    id: "increase-grid-load",
    label: "Zwiększ obciążenie sieci",
    cyberneticPart: "effector",
    description: "Nietrafiona reakcja zwiększa zakłócenie infrastruktury.",
    effects: { energy: -14, stress: 8, trust: -6 },
    badForMissionIds: ["power-outage"],
  },
  {
    id: "force-only",
    label: "Użyj wyłącznie przymusu",
    cyberneticPart: "effector",
    description: "Przymus bez informacji i zaufania może obniżyć porządek długoterminowy.",
    effects: { publicOrder: 4, trust: -14, stress: 10 },
    badForMissionIds: ["disinformation", "trust-crisis"],
  },
  {
    id: "hide-problem",
    label: "Ukryj problem",
    cyberneticPart: "correlator",
    description: "System zrywa pętlę informacji zwrotnej z mieszkańcami.",
    effects: { trust: -14, informationQuality: -12, stress: 8 },
    badForMissionIds: ["water-shortage", "trust-crisis", "power-outage"],
  },
  {
    id: "ignore-reports",
    label: "Zignoruj zgłoszenia",
    cyberneticPart: "receptor",
    description: "System odcina się od danych wejściowych. Decyzje będą opóźnione albo błędne.",
    effects: { informationQuality: -12, trust: -8, stress: 8 },
    badForMissionIds: ["power-outage", "disinformation", "traffic-jam", "water-shortage", "trust-crisis"],
    feedbackBad: "Ignorowanie receptorów społecznych odcina system od danych o własnym stanie.",
  },
];
