import type { Mission } from "../../types/game";

export const cityMissions: Mission[] = [
  {
    id: "power-outage",
    title: "Awaria zasilania",
    description: "W jednej z dzielnic spada napięcie. Mieszkańcy zgłaszają przerwy w dostawie prądu.",
    initialState: {
      energy: 34,
      water: 70,
      transport: 62,
      trust: 58,
      informationQuality: 42,
      publicOrder: 59,
      resourceReserve: 62,
      stress: 54,
      stability: 0,
    },
    targetExplanation:
      "awaria → czujniki i zgłoszenia → centrum danych → homeostat miasta → rezerwy energii → ekipy techniczne → feedback",
    recommendedActionIds: [
      "activate-grid-sensors",
      "analyze-in-city-hall",
      "check-city-homeostat",
      "use-energy-reserves",
      "repair-power-grid",
      "publish-transparent-message",
      "reduce-grid-load",
    ],
    dangerousActionIds: ["ignore-reports", "publish-empty-propaganda", "increase-grid-load", "hide-problem"],
    successCriteria: {
      energy: { min: 55 },
      informationQuality: { min: 55 },
      stress: { max: 52 },
      stability: { min: 58 },
    },
  },
  {
    id: "disinformation",
    title: "Dezinformacja w mieście",
    description: "W sieci krąży fałszywa informacja o skażeniu wody. Rośnie panika.",
    initialState: {
      energy: 66,
      water: 72,
      transport: 62,
      trust: 38,
      informationQuality: 28,
      publicOrder: 48,
      resourceReserve: 65,
      stress: 78,
      stability: 0,
    },
    targetExplanation:
      "plotka → receptory informacyjne → dane wodociągów → korelator komunikacji → dowody i sprostowanie → monitorowanie reakcji",
    recommendedActionIds: [
      "activate-social-listening",
      "activate-water-stations",
      "analyze-in-city-hall",
      "check-city-homeostat",
      "show-measurement-data",
      "publish-transparent-message",
      "reduce-message-overload",
    ],
    dangerousActionIds: ["force-only", "hide-problem", "ignore-reports", "publish-empty-propaganda"],
    successCriteria: {
      informationQuality: { min: 60 },
      trust: { min: 50 },
      stress: { max: 52 },
      stability: { min: 58 },
    },
  },
  {
    id: "traffic-jam",
    title: "Korek transportowy",
    description: "Węzeł drogowy jest przeciążony. Transport miejski traci płynność.",
    initialState: {
      energy: 63,
      water: 70,
      transport: 28,
      trust: 55,
      informationQuality: 44,
      publicOrder: 48,
      resourceReserve: 58,
      stress: 62,
      stability: 0,
    },
    targetExplanation:
      "korek → czujniki ruchu → analiza przepływów → homeostat → sygnalizacja, objazdy, służby → feedback",
    recommendedActionIds: [
      "activate-traffic-sensors",
      "analyze-in-city-hall",
      "check-city-homeostat",
      "adjust-traffic-lights",
      "reroute-traffic",
      "send-road-services",
      "publish-transparent-message",
    ],
    dangerousActionIds: ["ignore-reports", "close-main-road", "hide-problem"],
    successCriteria: {
      transport: { min: 52 },
      informationQuality: { min: 52 },
      publicOrder: { min: 50 },
      stability: { min: 56 },
    },
  },
  {
    id: "water-shortage",
    title: "Susza i spadek zasobów wody",
    description: "Poziom wody spada. Wodociągi ostrzegają przed przeciążeniem.",
    initialState: {
      energy: 64,
      water: 30,
      transport: 58,
      trust: 54,
      informationQuality: 45,
      publicOrder: 52,
      resourceReserve: 54,
      stress: 64,
      stability: 0,
    },
    targetExplanation:
      "susza → stacje pomiarowe → homeostat zasobów → ograniczenie zużycia i alternatywne dostawy → komunikaty → feedback",
    recommendedActionIds: [
      "activate-water-stations",
      "analyze-in-city-hall",
      "check-city-homeostat",
      "limit-nonessential-water-use",
      "open-water-reserves",
      "activate-alternative-supply",
      "publish-transparent-message",
    ],
    dangerousActionIds: ["hide-problem", "ignore-reports", "force-only", "use-energy-reserves"],
    successCriteria: {
      water: { min: 55 },
      resourceReserve: { min: 30 },
      informationQuality: { min: 55 },
      stability: { min: 56 },
    },
  },
  {
    id: "trust-crisis",
    title: "Kryzys zaufania",
    description: "Po serii chaotycznych decyzji spada zaufanie mieszkańców. Nawet dobre komunikaty nie działają.",
    initialState: {
      energy: 62,
      water: 66,
      transport: 55,
      trust: 22,
      informationQuality: 38,
      publicOrder: 42,
      resourceReserve: 56,
      stress: 72,
      stability: 0,
    },
    targetExplanation:
      "niska wiarygodność → receptory społeczne → analiza przyczyn → realne działania → fakty i wyniki → feedback zaufania",
    recommendedActionIds: [
      "activate-social-listening",
      "analyze-in-city-hall",
      "check-city-homeostat",
      "real-repair-actions",
      "show-measurement-data",
      "publish-transparent-message",
      "reduce-message-overload",
    ],
    dangerousActionIds: ["publish-empty-propaganda", "hide-problem", "force-only", "ignore-reports"],
    successCriteria: {
      trust: { min: 50 },
      informationQuality: { min: 55 },
      publicOrder: { min: 48 },
      stress: { max: 55 },
      stability: { min: 56 },
    },
  },
];
